# Generated by Django 2.1.3 on 2018-11-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181125_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='exercise',
            name='position',
            field=models.FloatField(default=0),
        ),
    ]
