# Generated by Django 2.1 on 2018-12-02 10:50

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_snippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['title']),
        ),
    ]
