# Generated by Django 2.1 on 2019-01-18 21:51

from django.db import migrations


def publish_existing(apps, schema_editor):
    Exercise = apps.get_model("website", "Exercise")
    for exercise in Exercise.objects.all():
        exercise.is_published = True
        exercise.save()


class Migration(migrations.Migration):

    dependencies = [("website", "0007_exercise_is_published")]

    operations = [migrations.RunPython(publish_existing)]
