# Generated by Django 2.1 on 2019-02-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
    ]
