# Generated by Django 3.0.8 on 2020-07-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_answer_is_shared"),
    ]

    operations = [
        migrations.DeleteModel(name="Lesson",),
    ]
