# Generated by Django 3.1.6 on 2021-04-11 19:06

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='check',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='initial_solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='solution',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='wording',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='wording_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='wording_fr',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
