# Generated by Django 3.0.8 on 2020-07-21 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_userstats'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
