# Generated by Django 3.1.6 on 2021-04-11 19:36

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20210411_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=42, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name'], unique=True),
        ),
    ]
