# Generated by Django 3.0.8 on 2020-07-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_userstats_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
