# Generated by Django 3.0.8 on 2020-09-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_exercise_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='wording_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='wording_fr',
            field=models.TextField(null=True),
        ),
    ]
