# Generated by Django 3.1.2 on 2020-10-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20200929_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='author',
        ),
    ]
