# Generated by Django 3.1.2 on 2020-11-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_auto_20201108_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='pre_check',
            field=models.TextField(blank=True, null=True),
        ),
    ]
