# Generated by Django 3.1.2 on 2020-11-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_exercise_pre_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_unhelpfull',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
