# Generated by Django 3.1.3 on 2020-12-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0002_auto_20201204_1148'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='UserStats',
        ),
    ]
