# Generated by Django 3.2.2 on 2021-11-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0002_delete_snippet'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['-points'], name='hkis_userin_points_d45d8e_idx'),
        ),
    ]
