# Generated by Django 3.1.3 on 2020-12-04 12:37

from django.db import migrations
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20201204_1307'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', website.models.UserManager()),
            ],
        ),
    ]
