# Generated by Django 3.2.2 on 2021-11-30 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0003_userinfo_hkis_userin_points_d45d8e_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='rank',
        ),
    ]
