# Generated by Django 3.2.2 on 2021-12-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0004_remove_userinfo_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='show_in_leaderboard',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['show_in_leaderboard', '-points'], name='hkis_userin_show_in_c1de31_idx'),
        ),
    ]
