# Generated by Django 3.2.2 on 2021-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0005_auto_20211201_0109'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['exercise', 'is_valid'], name='hkis_answer_exercis_656701_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['exercise', 'user', 'is_valid'], name='hkis_answer_exercis_4938f2_idx'),
        ),
    ]
