# Generated by Django 3.1.3 on 2020-12-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_exercise_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_profile',
            field=models.BooleanField(default=True),
        ),
    ]
