# Generated by Django 4.0.5 on 2022-06-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0007_exercise_solved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='check',
            new_name='check_py',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='pre_check',
            new_name='pre_check_py',
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_corrected',
            field=models.BooleanField(default=False, verbose_name='Corrected'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='Shared'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_unhelpfull',
            field=models.BooleanField(blank=True, default=False, verbose_name='Unhelpfull'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_valid',
            field=models.BooleanField(default=False, verbose_name='Valid'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='source_code',
            field=models.TextField(blank=True),
        ),
    ]
