# Generated by Django 3.1.3 on 2020-12-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0009_auto_20201214_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ('category__position', 'category', 'position')},
        ),
    ]
