# Generated by Django 3.1.2 on 2021-02-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0011_auto_20201218_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=512)),
                ('title_en', models.CharField(max_length=512, null=True)),
                ('title_fr', models.CharField(max_length=512, null=True)),
                ('body', models.TextField(blank=True, default='')),
                ('body_en', models.TextField(blank=True, default='', null=True)),
                ('body_fr', models.TextField(blank=True, default='', null=True)),
                ('position', models.FloatField(blank=True, default=0)),
                ('in_menu', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
