# Generated by Django 3.1.6 on 2021-05-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0017_auto_20210429_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
