# Generated by Django 3.2.2 on 2021-10-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0020_auto_20211004_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_safe',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
