# Generated by Django 3.2.2 on 2021-11-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0023_remove_exercise_solution'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='answer',
            name='hkis_ans_exercis_d8ffb5_idx',
        ),
        migrations.RemoveIndex(
            model_name='answer',
            name='hkis_ans_is_vali_c5790f_idx',
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['exercise', '-votes'], name='hkis_answer_exercis_f0b56e_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['is_valid', 'is_safe'], name='hkis_answer_is_vali_62f948_idx'),
        ),
    ]
