# Generated by Django 3.2.2 on 2021-11-27 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0025_userinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
    ]
