# Generated by Django 3.2.2 on 2021-11-27 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0026_auto_20211127_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='public_profile',
        ),
    ]
