# Generated by Django 3.2.2 on 2021-11-27 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hkis', '0028_auto_20211127_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
    ]
